name: Terraform Plan
on: 
  push:
    branches:
      - feature/*
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest 
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Terraform Plan
      run: |
        terraform init
        terraform validate
        terraform plan
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5.0.2
      with:
#        commit-message: update authors
#        title: Update AUTHORS
#        body: Credit new contributors by updating AUTHORS
        token: ${{ secrets.PAT }}
#        branch: master